apiVersion: batch/v1
kind: Job
metadata:
  name: hd-agent-secret-cleanup
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: hd-agent-secret-cleanup
    {{- include "hd.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hd-agent-secret-cleanup
        {{- include "hd.labels" . | nindent 8 }}
    spec:
      serviceAccountName: hd-agent-sa
      restartPolicy: Never
      containers:
        - name: hd-agent-secret-cleanup
          image: {{ if .Values.agent.image }}{{ .Values.agent.image }}{{ else }}{{ .Values.image }}{{ end }}
          imagePullPolicy: {{ if .Values.agent.image_pull_policy }}{{ .Values.agent.image_pull_policy }}{{ else }}{{ .Values.image_pull_policy }}{{ end }}
          command: ["java"]
          args: ["-cp", "/app/binary.jar", "com.fivetran.hybrid_deployment.controller.DeleteControllerSecretMain"]
          env:
            - name: namespace
              value: {{ .Release.Namespace }}
