name: Full Upstream Sync

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24=true

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-all:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v4.2.2 
        with:
          fetch-depth: 0

      - name: Sync Branch and Tags
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          gh repo sync ${{ github.repository }} --source "fivetran/hybrid_deployment" --branch "main"
          git remote add upstream https://github.com/fivetran/hybrid_deployment.git
          git fetch upstream --tags
          git push origin --tags --force
